/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ILendingCoreMethods } from "./ILendingCoreMethods";

export class ILendingCoreMethodsFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILendingCoreMethods {
    return new Contract(address, _abi, signerOrProvider) as ILendingCoreMethods;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
    ],
    name: "getLoanApprovalCost",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
    ],
    name: "getLoanApprovalCostOnly",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nrOfInstallments",
        type: "uint256",
      },
    ],
    name: "getLoanInstallmentCost",
    outputs: [
      {
        internalType: "uint256",
        name: "overallInstallmentAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "interestPerInstallement",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "interestDiscounted",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "interestToStaterPerInstallement",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountPaidAsInstallmentToLender",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
    ],
    name: "getLoanRemainToPay",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
    ],
    name: "getLoanStartEnd",
    outputs: [
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
