/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StaterDiscounts } from "./StaterDiscounts";

export { StaterDiscounts__factory } from "./factories/StaterDiscounts__factory";
