/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace LendingConstructor {
  export type StructStruct = { methods: string; discounts: string };

  export type StructStructOutput = [string, string] & {
    methods: string;
    discounts: string;
  };
}

export declare namespace CreateLoanParams {
  export type StructStruct = {
    loanAmount: BigNumberish;
    nrOfInstallments: BigNumberish;
    currency: string;
    assetsValue: BigNumberish;
    nftAddressArray: string[];
    nftTokenIdArray: BigNumberish[];
    nftTokenTypeArray: BigNumberish[];
  };

  export type StructStructOutput = [
    BigNumber,
    number,
    string,
    BigNumber,
    string[],
    BigNumber[],
    number[]
  ] & {
    loanAmount: BigNumber;
    nrOfInstallments: number;
    currency: string;
    assetsValue: BigNumber;
    nftAddressArray: string[];
    nftTokenIdArray: BigNumber[];
    nftTokenTypeArray: number[];
  };
}

export declare namespace EditLoanParams {
  export type StructStruct = {
    loanId: BigNumberish;
    loanAmount: BigNumberish;
    nrOfInstallments: BigNumberish;
    currency: string;
    assetsValue: BigNumberish;
    installmentTime: BigNumberish;
  };

  export type StructStructOutput = [
    BigNumber,
    BigNumber,
    number,
    string,
    BigNumber,
    BigNumber
  ] & {
    loanId: BigNumber;
    loanAmount: BigNumber;
    nrOfInstallments: number;
    currency: string;
    assetsValue: BigNumber;
    installmentTime: BigNumber;
  };
}

export interface LendingTemplateInterface extends utils.Interface {
  contractName: "LendingTemplate";
  functions: {
    "approveLoan(uint256)": FunctionFragment;
    "canBeTerminated(uint256)": FunctionFragment;
    "cancelLoan(uint256)": FunctionFragment;
    "checkLtv(uint256,uint256)": FunctionFragment;
    "checkTokensApproval(address,address)": FunctionFragment;
    "createLoan((uint256,uint16,address,uint256,address[],uint256[],uint8[]))": FunctionFragment;
    "discounts()": FunctionFragment;
    "editLoan((uint256,uint256,uint16,address,uint256,uint256))": FunctionFragment;
    "getLoanApprovalCost(uint256)": FunctionFragment;
    "getLoanInstallmentCost(uint256,uint256)": FunctionFragment;
    "getLoanRemainToPay(uint256)": FunctionFragment;
    "getLoanStartEnd(uint256)": FunctionFragment;
    "id()": FunctionFragment;
    "interestRate()": FunctionFragment;
    "interestRateToStater()": FunctionFragment;
    "lenderFee()": FunctionFragment;
    "lendingMethodsAddress()": FunctionFragment;
    "loans(uint256)": FunctionFragment;
    "ltv()": FunctionFragment;
    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "payLoan(uint256,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setGlobalVariables(uint256,uint256,uint256,uint32,address,address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "terminateLoan(uint256)": FunctionFragment;
    "transferItems(address,address,address[],uint256[],uint8[])": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transferTokens(address,address,address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "approveLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canBeTerminated",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkLtv",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTokensApproval",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createLoan",
    values: [CreateLoanParams.StructStruct]
  ): string;
  encodeFunctionData(functionFragment: "discounts", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "editLoan",
    values: [EditLoanParams.StructStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanApprovalCost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanInstallmentCost",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanRemainToPay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanStartEnd",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "id", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "interestRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "interestRateToStater",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lenderFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lendingMethodsAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "ltv", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [string, string, BigNumberish[], BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payLoan",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGlobalVariables",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "terminateLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferItems",
    values: [string, string, string[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferTokens",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canBeTerminated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkLtv", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkTokensApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "discounts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "editLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLoanApprovalCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanInstallmentCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanRemainToPay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanStartEnd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "id", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "interestRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interestRateToStater",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lenderFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lendingMethodsAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ltv", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalVariables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "terminateLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferTokens",
    data: BytesLike
  ): Result;

  events: {
    "CloseLoanOffer(uint256,address,uint256)": EventFragment;
    "EditLoan(address,uint256,uint256,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "ItemsWithdrawn(address,uint256,uint8)": EventFragment;
    "LoanApproved(address,uint256,uint256)": EventFragment;
    "LoanCancelled(uint256)": EventFragment;
    "LoanOffer(uint256,address,uint256,uint256)": EventFragment;
    "LoanOfferApproved(address,uint256,uint256,uint256,uint256)": EventFragment;
    "LoanPayment(uint256,uint256,uint256,uint256,uint256,uint8)": EventFragment;
    "NewLoan(address,address,uint256,address[],uint256[],uint8[])": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CloseLoanOffer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EditLoan"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ItemsWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanApproved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanOffer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanOfferApproved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanPayment"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewLoan"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type CloseLoanOfferEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  { loanId: BigNumber; offerer: string; position: BigNumber }
>;

export type CloseLoanOfferEventFilter = TypedEventFilter<CloseLoanOfferEvent>;

export type EditLoanEvent = TypedEvent<
  [
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ],
  {
    currency: string;
    loanId: BigNumber;
    loanAmount: BigNumber;
    amountDue: BigNumber;
    installmentAmount: BigNumber;
    assetsValue: BigNumber;
    frequencyTime: BigNumber;
    frequencyTimeUnit: BigNumber;
  }
>;

export type EditLoanEventFilter = TypedEventFilter<EditLoanEvent>;

export type ItemsWithdrawnEvent = TypedEvent<
  [string, BigNumber, number],
  { requester: string; loanId: BigNumber; status: number }
>;

export type ItemsWithdrawnEventFilter = TypedEventFilter<ItemsWithdrawnEvent>;

export type LoanApprovedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { lender: string; loanId: BigNumber; loanPaymentEnd: BigNumber }
>;

export type LoanApprovedEventFilter = TypedEventFilter<LoanApprovedEvent>;

export type LoanCancelledEvent = TypedEvent<[BigNumber], { loanId: BigNumber }>;

export type LoanCancelledEventFilter = TypedEventFilter<LoanCancelledEvent>;

export type LoanOfferEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  {
    loanId: BigNumber;
    offerer: string;
    offerId: BigNumber;
    position: BigNumber;
  }
>;

export type LoanOfferEventFilter = TypedEventFilter<LoanOfferEvent>;

export type LoanOfferApprovedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    lender: string;
    loanId: BigNumber;
    offerId: BigNumber;
    offerAmount: BigNumber;
    loanPaymentEnd: BigNumber;
  }
>;

export type LoanOfferApprovedEventFilter =
  TypedEventFilter<LoanOfferApprovedEvent>;

export type LoanPaymentEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, number],
  {
    loanId: BigNumber;
    installmentAmount: BigNumber;
    amountPaidAsInstallmentToLender: BigNumber;
    interestPerInstallement: BigNumber;
    interestToStaterPerInstallement: BigNumber;
    status: number;
  }
>;

export type LoanPaymentEventFilter = TypedEventFilter<LoanPaymentEvent>;

export type NewLoanEvent = TypedEvent<
  [string, string, BigNumber, string[], BigNumber[], number[]],
  {
    owner: string;
    currency: string;
    loanId: BigNumber;
    nftAddressArray: string[];
    nftTokenIdArray: BigNumber[];
    nftTokenTypeArray: number[];
  }
>;

export type NewLoanEventFilter = TypedEventFilter<NewLoanEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface LendingTemplate extends BaseContract {
  contractName: "LendingTemplate";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LendingTemplateInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    approveLoan(
      loanId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "approveLoan(uint256)"(
      loanId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    canBeTerminated(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "canBeTerminated(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    cancelLoan(
      loanId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "cancelLoan(uint256)"(
      loanId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    checkLtv(
      loanValue: BigNumberish,
      assetsValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "checkLtv(uint256,uint256)"(
      loanValue: BigNumberish,
      assetsValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    checkTokensApproval(
      from: string,
      currency: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "checkTokensApproval(address,address)"(
      from: string,
      currency: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    createLoan(
      input: CreateLoanParams.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "createLoan((uint256,uint16,address,uint256,address[],uint256[],uint8[]))"(
      input: CreateLoanParams.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    discounts(overrides?: CallOverrides): Promise<[string]>;

    "discounts()"(overrides?: CallOverrides): Promise<[string]>;

    editLoan(
      input: EditLoanParams.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "editLoan((uint256,uint256,uint16,address,uint256,uint256))"(
      input: EditLoanParams.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getLoanApprovalCost(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber, string]>;

    "getLoanApprovalCost(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber, string]>;

    getLoanInstallmentCost(
      loanId: BigNumberish,
      nrOfInstallments: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        overallInstallmentAmount: BigNumber;
        interestPerInstallement: BigNumber;
        interestDiscounted: BigNumber;
        interestToStaterPerInstallement: BigNumber;
        amountPaidAsInstallmentToLender: BigNumber;
      }
    >;

    "getLoanInstallmentCost(uint256,uint256)"(
      loanId: BigNumberish,
      nrOfInstallments: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        overallInstallmentAmount: BigNumber;
        interestPerInstallement: BigNumber;
        interestDiscounted: BigNumber;
        interestToStaterPerInstallement: BigNumber;
        amountPaidAsInstallmentToLender: BigNumber;
      }
    >;

    getLoanRemainToPay(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getLoanRemainToPay(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getLoanStartEnd(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[[BigNumber, BigNumber]]>;

    "getLoanStartEnd(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[[BigNumber, BigNumber]]>;

    id(overrides?: CallOverrides): Promise<[BigNumber]>;

    "id()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    interestRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    "interestRate()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    interestRateToStater(overrides?: CallOverrides): Promise<[BigNumber]>;

    "interestRateToStater()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    lenderFee(overrides?: CallOverrides): Promise<[number]>;

    "lenderFee()"(overrides?: CallOverrides): Promise<[number]>;

    lendingMethodsAddress(overrides?: CallOverrides): Promise<[string]>;

    "lendingMethodsAddress()"(overrides?: CallOverrides): Promise<[string]>;

    loans(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        number,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        number
      ] & {
        borrower: string;
        lender: string;
        currency: string;
        status: number;
        installmentTime: BigNumber;
        nrOfPayments: BigNumber;
        loanAmount: BigNumber;
        assetsValue: BigNumber;
        installmentAmount: BigNumber;
        amountDue: BigNumber;
        paidAmount: BigNumber;
        nrOfInstallments: number;
        defaultingLimit: number;
      }
    >;

    "loans(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        number,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        number
      ] & {
        borrower: string;
        lender: string;
        currency: string;
        status: number;
        installmentTime: BigNumber;
        nrOfPayments: BigNumber;
        loanAmount: BigNumber;
        assetsValue: BigNumber;
        installmentAmount: BigNumber;
        amountDue: BigNumber;
        paidAmount: BigNumber;
        nrOfInstallments: number;
        defaultingLimit: number;
      }
    >;

    ltv(overrides?: CallOverrides): Promise<[BigNumber]>;

    "ltv()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "onERC1155Received(address,address,uint256,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    payLoan(
      loanId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "payLoan(uint256,uint256)"(
      loanId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGlobalVariables(
      _ltv: BigNumberish,
      _interestRate: BigNumberish,
      _interestRateToStater: BigNumberish,
      _lenderFee: BigNumberish,
      _lendingMethodsAddress: string,
      _lendingDiscountsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setGlobalVariables(uint256,uint256,uint256,uint32,address,address)"(
      _ltv: BigNumberish,
      _interestRate: BigNumberish,
      _interestRateToStater: BigNumberish,
      _lenderFee: BigNumberish,
      _lendingMethodsAddress: string,
      _lendingDiscountsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    terminateLoan(
      loanId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "terminateLoan(uint256)"(
      loanId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferItems(
      from: string,
      to: string,
      nftAddressArray: string[],
      nftTokenIdArray: BigNumberish[],
      nftTokenTypeArray: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferItems(address,address,address[],uint256[],uint8[])"(
      from: string,
      to: string,
      nftAddressArray: string[],
      nftTokenIdArray: BigNumberish[],
      nftTokenTypeArray: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferTokens(
      from: string,
      to: string,
      currency: string,
      qty1: BigNumberish,
      qty2: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferTokens(address,address,address,uint256,uint256)"(
      from: string,
      to: string,
      currency: string,
      qty1: BigNumberish,
      qty2: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  approveLoan(
    loanId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "approveLoan(uint256)"(
    loanId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  canBeTerminated(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "canBeTerminated(uint256)"(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  cancelLoan(
    loanId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "cancelLoan(uint256)"(
    loanId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  checkLtv(
    loanValue: BigNumberish,
    assetsValue: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "checkLtv(uint256,uint256)"(
    loanValue: BigNumberish,
    assetsValue: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  checkTokensApproval(
    from: string,
    currency: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "checkTokensApproval(address,address)"(
    from: string,
    currency: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  createLoan(
    input: CreateLoanParams.StructStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "createLoan((uint256,uint16,address,uint256,address[],uint256[],uint8[]))"(
    input: CreateLoanParams.StructStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  discounts(overrides?: CallOverrides): Promise<string>;

  "discounts()"(overrides?: CallOverrides): Promise<string>;

  editLoan(
    input: EditLoanParams.StructStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "editLoan((uint256,uint256,uint16,address,uint256,uint256))"(
    input: EditLoanParams.StructStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getLoanApprovalCost(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber, string]>;

  "getLoanApprovalCost(uint256)"(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber, string]>;

  getLoanInstallmentCost(
    loanId: BigNumberish,
    nrOfInstallments: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      overallInstallmentAmount: BigNumber;
      interestPerInstallement: BigNumber;
      interestDiscounted: BigNumber;
      interestToStaterPerInstallement: BigNumber;
      amountPaidAsInstallmentToLender: BigNumber;
    }
  >;

  "getLoanInstallmentCost(uint256,uint256)"(
    loanId: BigNumberish,
    nrOfInstallments: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      overallInstallmentAmount: BigNumber;
      interestPerInstallement: BigNumber;
      interestDiscounted: BigNumber;
      interestToStaterPerInstallement: BigNumber;
      amountPaidAsInstallmentToLender: BigNumber;
    }
  >;

  getLoanRemainToPay(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getLoanRemainToPay(uint256)"(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLoanStartEnd(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  "getLoanStartEnd(uint256)"(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  id(overrides?: CallOverrides): Promise<BigNumber>;

  "id()"(overrides?: CallOverrides): Promise<BigNumber>;

  interestRate(overrides?: CallOverrides): Promise<BigNumber>;

  "interestRate()"(overrides?: CallOverrides): Promise<BigNumber>;

  interestRateToStater(overrides?: CallOverrides): Promise<BigNumber>;

  "interestRateToStater()"(overrides?: CallOverrides): Promise<BigNumber>;

  lenderFee(overrides?: CallOverrides): Promise<number>;

  "lenderFee()"(overrides?: CallOverrides): Promise<number>;

  lendingMethodsAddress(overrides?: CallOverrides): Promise<string>;

  "lendingMethodsAddress()"(overrides?: CallOverrides): Promise<string>;

  loans(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      number,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      number,
      number
    ] & {
      borrower: string;
      lender: string;
      currency: string;
      status: number;
      installmentTime: BigNumber;
      nrOfPayments: BigNumber;
      loanAmount: BigNumber;
      assetsValue: BigNumber;
      installmentAmount: BigNumber;
      amountDue: BigNumber;
      paidAmount: BigNumber;
      nrOfInstallments: number;
      defaultingLimit: number;
    }
  >;

  "loans(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      number,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      number,
      number
    ] & {
      borrower: string;
      lender: string;
      currency: string;
      status: number;
      installmentTime: BigNumber;
      nrOfPayments: BigNumber;
      loanAmount: BigNumber;
      assetsValue: BigNumber;
      installmentAmount: BigNumber;
      amountDue: BigNumber;
      paidAmount: BigNumber;
      nrOfInstallments: number;
      defaultingLimit: number;
    }
  >;

  ltv(overrides?: CallOverrides): Promise<BigNumber>;

  "ltv()"(overrides?: CallOverrides): Promise<BigNumber>;

  onERC1155BatchReceived(
    arg0: string,
    arg1: string,
    arg2: BigNumberish[],
    arg3: BigNumberish[],
    arg4: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
    arg0: string,
    arg1: string,
    arg2: BigNumberish[],
    arg3: BigNumberish[],
    arg4: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC1155Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BigNumberish,
    arg4: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "onERC1155Received(address,address,uint256,uint256,bytes)"(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BigNumberish,
    arg4: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC721Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "onERC721Received(address,address,uint256,bytes)"(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  payLoan(
    loanId: BigNumberish,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "payLoan(uint256,uint256)"(
    loanId: BigNumberish,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "renounceOwnership()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGlobalVariables(
    _ltv: BigNumberish,
    _interestRate: BigNumberish,
    _interestRateToStater: BigNumberish,
    _lenderFee: BigNumberish,
    _lendingMethodsAddress: string,
    _lendingDiscountsAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setGlobalVariables(uint256,uint256,uint256,uint32,address,address)"(
    _ltv: BigNumberish,
    _interestRate: BigNumberish,
    _interestRateToStater: BigNumberish,
    _lenderFee: BigNumberish,
    _lendingMethodsAddress: string,
    _lendingDiscountsAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "supportsInterface(bytes4)"(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  terminateLoan(
    loanId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "terminateLoan(uint256)"(
    loanId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferItems(
    from: string,
    to: string,
    nftAddressArray: string[],
    nftTokenIdArray: BigNumberish[],
    nftTokenTypeArray: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferItems(address,address,address[],uint256[],uint8[])"(
    from: string,
    to: string,
    nftAddressArray: string[],
    nftTokenIdArray: BigNumberish[],
    nftTokenTypeArray: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferTokens(
    from: string,
    to: string,
    currency: string,
    qty1: BigNumberish,
    qty2: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferTokens(address,address,address,uint256,uint256)"(
    from: string,
    to: string,
    currency: string,
    qty1: BigNumberish,
    qty2: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    approveLoan(loanId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "approveLoan(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    canBeTerminated(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "canBeTerminated(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    cancelLoan(loanId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "cancelLoan(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    checkLtv(
      loanValue: BigNumberish,
      assetsValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkLtv(uint256,uint256)"(
      loanValue: BigNumberish,
      assetsValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    checkTokensApproval(
      from: string,
      currency: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkTokensApproval(address,address)"(
      from: string,
      currency: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createLoan(
      input: CreateLoanParams.StructStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    "createLoan((uint256,uint16,address,uint256,address[],uint256[],uint8[]))"(
      input: CreateLoanParams.StructStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    discounts(overrides?: CallOverrides): Promise<string>;

    "discounts()"(overrides?: CallOverrides): Promise<string>;

    editLoan(
      input: EditLoanParams.StructStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    "editLoan((uint256,uint256,uint16,address,uint256,uint256))"(
      input: EditLoanParams.StructStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    getLoanApprovalCost(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber, string]>;

    "getLoanApprovalCost(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber, string]>;

    getLoanInstallmentCost(
      loanId: BigNumberish,
      nrOfInstallments: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        overallInstallmentAmount: BigNumber;
        interestPerInstallement: BigNumber;
        interestDiscounted: BigNumber;
        interestToStaterPerInstallement: BigNumber;
        amountPaidAsInstallmentToLender: BigNumber;
      }
    >;

    "getLoanInstallmentCost(uint256,uint256)"(
      loanId: BigNumberish,
      nrOfInstallments: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        overallInstallmentAmount: BigNumber;
        interestPerInstallement: BigNumber;
        interestDiscounted: BigNumber;
        interestToStaterPerInstallement: BigNumber;
        amountPaidAsInstallmentToLender: BigNumber;
      }
    >;

    getLoanRemainToPay(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLoanRemainToPay(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLoanStartEnd(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "getLoanStartEnd(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    id(overrides?: CallOverrides): Promise<BigNumber>;

    "id()"(overrides?: CallOverrides): Promise<BigNumber>;

    interestRate(overrides?: CallOverrides): Promise<BigNumber>;

    "interestRate()"(overrides?: CallOverrides): Promise<BigNumber>;

    interestRateToStater(overrides?: CallOverrides): Promise<BigNumber>;

    "interestRateToStater()"(overrides?: CallOverrides): Promise<BigNumber>;

    lenderFee(overrides?: CallOverrides): Promise<number>;

    "lenderFee()"(overrides?: CallOverrides): Promise<number>;

    lendingMethodsAddress(overrides?: CallOverrides): Promise<string>;

    "lendingMethodsAddress()"(overrides?: CallOverrides): Promise<string>;

    loans(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        number,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        number
      ] & {
        borrower: string;
        lender: string;
        currency: string;
        status: number;
        installmentTime: BigNumber;
        nrOfPayments: BigNumber;
        loanAmount: BigNumber;
        assetsValue: BigNumber;
        installmentAmount: BigNumber;
        amountDue: BigNumber;
        paidAmount: BigNumber;
        nrOfInstallments: number;
        defaultingLimit: number;
      }
    >;

    "loans(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        number,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        number
      ] & {
        borrower: string;
        lender: string;
        currency: string;
        status: number;
        installmentTime: BigNumber;
        nrOfPayments: BigNumber;
        loanAmount: BigNumber;
        assetsValue: BigNumber;
        installmentAmount: BigNumber;
        amountDue: BigNumber;
        paidAmount: BigNumber;
        nrOfInstallments: number;
        defaultingLimit: number;
      }
    >;

    ltv(overrides?: CallOverrides): Promise<BigNumber>;

    "ltv()"(overrides?: CallOverrides): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC1155Received(address,address,uint256,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    payLoan(
      loanId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "payLoan(uint256,uint256)"(
      loanId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    setGlobalVariables(
      _ltv: BigNumberish,
      _interestRate: BigNumberish,
      _interestRateToStater: BigNumberish,
      _lenderFee: BigNumberish,
      _lendingMethodsAddress: string,
      _lendingDiscountsAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setGlobalVariables(uint256,uint256,uint256,uint32,address,address)"(
      _ltv: BigNumberish,
      _interestRate: BigNumberish,
      _interestRateToStater: BigNumberish,
      _lenderFee: BigNumberish,
      _lendingMethodsAddress: string,
      _lendingDiscountsAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    terminateLoan(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "terminateLoan(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferItems(
      from: string,
      to: string,
      nftAddressArray: string[],
      nftTokenIdArray: BigNumberish[],
      nftTokenTypeArray: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "transferItems(address,address,address[],uint256[],uint8[])"(
      from: string,
      to: string,
      nftAddressArray: string[],
      nftTokenIdArray: BigNumberish[],
      nftTokenTypeArray: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferTokens(
      from: string,
      to: string,
      currency: string,
      qty1: BigNumberish,
      qty2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferTokens(address,address,address,uint256,uint256)"(
      from: string,
      to: string,
      currency: string,
      qty1: BigNumberish,
      qty2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CloseLoanOffer(uint256,address,uint256)"(
      loanId?: BigNumberish | null,
      offerer?: string | null,
      position?: BigNumberish | null
    ): CloseLoanOfferEventFilter;
    CloseLoanOffer(
      loanId?: BigNumberish | null,
      offerer?: string | null,
      position?: BigNumberish | null
    ): CloseLoanOfferEventFilter;

    "EditLoan(address,uint256,uint256,uint256,uint256,uint256,uint256,uint256)"(
      currency?: string | null,
      loanId?: BigNumberish | null,
      loanAmount?: null,
      amountDue?: null,
      installmentAmount?: null,
      assetsValue?: null,
      frequencyTime?: null,
      frequencyTimeUnit?: null
    ): EditLoanEventFilter;
    EditLoan(
      currency?: string | null,
      loanId?: BigNumberish | null,
      loanAmount?: null,
      amountDue?: null,
      installmentAmount?: null,
      assetsValue?: null,
      frequencyTime?: null,
      frequencyTimeUnit?: null
    ): EditLoanEventFilter;

    "ItemsWithdrawn(address,uint256,uint8)"(
      requester?: string | null,
      loanId?: BigNumberish | null,
      status?: null
    ): ItemsWithdrawnEventFilter;
    ItemsWithdrawn(
      requester?: string | null,
      loanId?: BigNumberish | null,
      status?: null
    ): ItemsWithdrawnEventFilter;

    "LoanApproved(address,uint256,uint256)"(
      lender?: string | null,
      loanId?: BigNumberish | null,
      loanPaymentEnd?: null
    ): LoanApprovedEventFilter;
    LoanApproved(
      lender?: string | null,
      loanId?: BigNumberish | null,
      loanPaymentEnd?: null
    ): LoanApprovedEventFilter;

    "LoanCancelled(uint256)"(
      loanId?: BigNumberish | null
    ): LoanCancelledEventFilter;
    LoanCancelled(loanId?: BigNumberish | null): LoanCancelledEventFilter;

    "LoanOffer(uint256,address,uint256,uint256)"(
      loanId?: BigNumberish | null,
      offerer?: string | null,
      offerId?: null,
      position?: BigNumberish | null
    ): LoanOfferEventFilter;
    LoanOffer(
      loanId?: BigNumberish | null,
      offerer?: string | null,
      offerId?: null,
      position?: BigNumberish | null
    ): LoanOfferEventFilter;

    "LoanOfferApproved(address,uint256,uint256,uint256,uint256)"(
      lender?: string | null,
      loanId?: BigNumberish | null,
      offerId?: BigNumberish | null,
      offerAmount?: null,
      loanPaymentEnd?: null
    ): LoanOfferApprovedEventFilter;
    LoanOfferApproved(
      lender?: string | null,
      loanId?: BigNumberish | null,
      offerId?: BigNumberish | null,
      offerAmount?: null,
      loanPaymentEnd?: null
    ): LoanOfferApprovedEventFilter;

    "LoanPayment(uint256,uint256,uint256,uint256,uint256,uint8)"(
      loanId?: BigNumberish | null,
      installmentAmount?: null,
      amountPaidAsInstallmentToLender?: null,
      interestPerInstallement?: null,
      interestToStaterPerInstallement?: null,
      status?: null
    ): LoanPaymentEventFilter;
    LoanPayment(
      loanId?: BigNumberish | null,
      installmentAmount?: null,
      amountPaidAsInstallmentToLender?: null,
      interestPerInstallement?: null,
      interestToStaterPerInstallement?: null,
      status?: null
    ): LoanPaymentEventFilter;

    "NewLoan(address,address,uint256,address[],uint256[],uint8[])"(
      owner?: string | null,
      currency?: string | null,
      loanId?: BigNumberish | null,
      nftAddressArray?: null,
      nftTokenIdArray?: null,
      nftTokenTypeArray?: null
    ): NewLoanEventFilter;
    NewLoan(
      owner?: string | null,
      currency?: string | null,
      loanId?: BigNumberish | null,
      nftAddressArray?: null,
      nftTokenIdArray?: null,
      nftTokenTypeArray?: null
    ): NewLoanEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    approveLoan(
      loanId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "approveLoan(uint256)"(
      loanId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    canBeTerminated(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "canBeTerminated(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelLoan(
      loanId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "cancelLoan(uint256)"(
      loanId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    checkLtv(
      loanValue: BigNumberish,
      assetsValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkLtv(uint256,uint256)"(
      loanValue: BigNumberish,
      assetsValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkTokensApproval(
      from: string,
      currency: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkTokensApproval(address,address)"(
      from: string,
      currency: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createLoan(
      input: CreateLoanParams.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "createLoan((uint256,uint16,address,uint256,address[],uint256[],uint8[]))"(
      input: CreateLoanParams.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    discounts(overrides?: CallOverrides): Promise<BigNumber>;

    "discounts()"(overrides?: CallOverrides): Promise<BigNumber>;

    editLoan(
      input: EditLoanParams.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "editLoan((uint256,uint256,uint16,address,uint256,uint256))"(
      input: EditLoanParams.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getLoanApprovalCost(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLoanApprovalCost(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLoanInstallmentCost(
      loanId: BigNumberish,
      nrOfInstallments: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLoanInstallmentCost(uint256,uint256)"(
      loanId: BigNumberish,
      nrOfInstallments: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLoanRemainToPay(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLoanRemainToPay(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLoanStartEnd(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLoanStartEnd(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    id(overrides?: CallOverrides): Promise<BigNumber>;

    "id()"(overrides?: CallOverrides): Promise<BigNumber>;

    interestRate(overrides?: CallOverrides): Promise<BigNumber>;

    "interestRate()"(overrides?: CallOverrides): Promise<BigNumber>;

    interestRateToStater(overrides?: CallOverrides): Promise<BigNumber>;

    "interestRateToStater()"(overrides?: CallOverrides): Promise<BigNumber>;

    lenderFee(overrides?: CallOverrides): Promise<BigNumber>;

    "lenderFee()"(overrides?: CallOverrides): Promise<BigNumber>;

    lendingMethodsAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "lendingMethodsAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    loans(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "loans(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ltv(overrides?: CallOverrides): Promise<BigNumber>;

    "ltv()"(overrides?: CallOverrides): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "onERC1155Received(address,address,uint256,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    payLoan(
      loanId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "payLoan(uint256,uint256)"(
      loanId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGlobalVariables(
      _ltv: BigNumberish,
      _interestRate: BigNumberish,
      _interestRateToStater: BigNumberish,
      _lenderFee: BigNumberish,
      _lendingMethodsAddress: string,
      _lendingDiscountsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setGlobalVariables(uint256,uint256,uint256,uint32,address,address)"(
      _ltv: BigNumberish,
      _interestRate: BigNumberish,
      _interestRateToStater: BigNumberish,
      _lenderFee: BigNumberish,
      _lendingMethodsAddress: string,
      _lendingDiscountsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    terminateLoan(
      loanId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "terminateLoan(uint256)"(
      loanId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferItems(
      from: string,
      to: string,
      nftAddressArray: string[],
      nftTokenIdArray: BigNumberish[],
      nftTokenTypeArray: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferItems(address,address,address[],uint256[],uint8[])"(
      from: string,
      to: string,
      nftAddressArray: string[],
      nftTokenIdArray: BigNumberish[],
      nftTokenTypeArray: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferTokens(
      from: string,
      to: string,
      currency: string,
      qty1: BigNumberish,
      qty2: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferTokens(address,address,address,uint256,uint256)"(
      from: string,
      to: string,
      currency: string,
      qty1: BigNumberish,
      qty2: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approveLoan(
      loanId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "approveLoan(uint256)"(
      loanId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    canBeTerminated(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "canBeTerminated(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelLoan(
      loanId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "cancelLoan(uint256)"(
      loanId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    checkLtv(
      loanValue: BigNumberish,
      assetsValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkLtv(uint256,uint256)"(
      loanValue: BigNumberish,
      assetsValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkTokensApproval(
      from: string,
      currency: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkTokensApproval(address,address)"(
      from: string,
      currency: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createLoan(
      input: CreateLoanParams.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "createLoan((uint256,uint16,address,uint256,address[],uint256[],uint8[]))"(
      input: CreateLoanParams.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    discounts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "discounts()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    editLoan(
      input: EditLoanParams.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "editLoan((uint256,uint256,uint16,address,uint256,uint256))"(
      input: EditLoanParams.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getLoanApprovalCost(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLoanApprovalCost(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLoanInstallmentCost(
      loanId: BigNumberish,
      nrOfInstallments: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLoanInstallmentCost(uint256,uint256)"(
      loanId: BigNumberish,
      nrOfInstallments: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLoanRemainToPay(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLoanRemainToPay(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLoanStartEnd(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLoanStartEnd(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    id(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "id()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    interestRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "interestRate()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    interestRateToStater(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "interestRateToStater()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lenderFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lenderFee()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lendingMethodsAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "lendingMethodsAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    loans(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "loans(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ltv(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ltv()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "onERC1155Received(address,address,uint256,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payLoan(
      loanId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "payLoan(uint256,uint256)"(
      loanId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGlobalVariables(
      _ltv: BigNumberish,
      _interestRate: BigNumberish,
      _interestRateToStater: BigNumberish,
      _lenderFee: BigNumberish,
      _lendingMethodsAddress: string,
      _lendingDiscountsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setGlobalVariables(uint256,uint256,uint256,uint32,address,address)"(
      _ltv: BigNumberish,
      _interestRate: BigNumberish,
      _interestRateToStater: BigNumberish,
      _lenderFee: BigNumberish,
      _lendingMethodsAddress: string,
      _lendingDiscountsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    terminateLoan(
      loanId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "terminateLoan(uint256)"(
      loanId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferItems(
      from: string,
      to: string,
      nftAddressArray: string[],
      nftTokenIdArray: BigNumberish[],
      nftTokenTypeArray: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferItems(address,address,address[],uint256[],uint8[])"(
      from: string,
      to: string,
      nftAddressArray: string[],
      nftTokenIdArray: BigNumberish[],
      nftTokenTypeArray: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferTokens(
      from: string,
      to: string,
      currency: string,
      qty1: BigNumberish,
      qty2: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferTokens(address,address,address,uint256,uint256)"(
      from: string,
      to: string,
      currency: string,
      qty1: BigNumberish,
      qty2: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
