/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface ILendingTemplateInterface extends utils.Interface {
  contractName: "ILendingTemplate";
  functions: {
    "canBeTerminated(uint256)": FunctionFragment;
    "getLoanApprovalCost(uint256)": FunctionFragment;
    "getPromissoryPermission(uint256)": FunctionFragment;
    "promissoryExchange(address,address,uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "canBeTerminated",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanApprovalCost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPromissoryPermission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "promissoryExchange",
    values: [string, string, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "canBeTerminated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanApprovalCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPromissoryPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "promissoryExchange",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ILendingTemplate extends BaseContract {
  contractName: "ILendingTemplate";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ILendingTemplateInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    canBeTerminated(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getLoanApprovalCost(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber, string]>;

    getPromissoryPermission(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    promissoryExchange(
      from: string,
      to: string,
      loanIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  canBeTerminated(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getLoanApprovalCost(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber, string]>;

  getPromissoryPermission(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  promissoryExchange(
    from: string,
    to: string,
    loanIds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    canBeTerminated(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getLoanApprovalCost(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber, string]>;

    getPromissoryPermission(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    promissoryExchange(
      from: string,
      to: string,
      loanIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    canBeTerminated(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLoanApprovalCost(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPromissoryPermission(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    promissoryExchange(
      from: string,
      to: string,
      loanIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    canBeTerminated(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLoanApprovalCost(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPromissoryPermission(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    promissoryExchange(
      from: string,
      to: string,
      loanIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
